#!/usr/bin/env sh

# yabai status bar
yabai -m config status_bar                      off

# global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   off
yabai -m config window_border                   on
yabai -m config window_border_placement         inset
yabai -m config window_border_width             2
yabai -m config window_border_radius            3
yabai -m config active_window_border_color      0xffff0000
yabai -m config normal_window_border_color      0xff202020
yabai -m config insert_window_border_color      0xff202020
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
yabai -m config bottom_padding                  0
yabai -m config left_padding                    0
yabai -m config right_padding                   0
yabai -m config window_gap                      2

yabai -m config window_topmost                  on
yabai -m config window_shadow                   float


# Web & Slack | Space 1
yabai -m rule --add app="Firefox Developer Edition" space=1
yabai -m rule --add app="Slack" space=1
yabai -m rule --add app="Chrome" space=1
yabai -m rule --add app="Spotify" space=1
yabai -m rule --add app="zoom.us" space=1

# IDE & Editors | Space 3
yabai -m rule --add app="Visual Studio Code" space=3 # Visual Studio Code
yabai -m rule --add app="Code" space=3 # Visual Studio Code
yabai -m rule --add app="Sourcetree" space=3 # Sourcetree

# Float | Space 4
yabai -m config --space 4 layout float
yabai -m rule --add app="^System Preferences$" space=4
yabai -m rule --add app="^System Preferences$"  manage=off border=off